server:
  port: 9001
spring:
  application:
    name: PRODUCT
  eureka:
     client:
       register-with-eureka: true
       fetch-registry: true
       serviceUrl:
         defaultZone: http://localhost:8761/eureka/
       instance:
         hostname: localhost